name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/ci.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/ci.yml'

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: Elbandi/github-workflows/.github/workflows/artifacts.yaml@v1
    with:
      repository: ${{ github.repository }}
      publish: ${{ github.event_name == 'push' }}
    secrets:
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ github.token }}
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
