name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/pkgs-delete.yml'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/pkgs-delete.yml'

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: Elbandi/github-workflows/.github/workflows/artifacts.yaml@v1
    with:
      publish: ${{ github.event_name == 'push' }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
