name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: Elbandi/github-workflows/.github/workflows/artifacts.yaml@v1
    with:
      publish: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
